---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[formsender::build_essential]
      - recipe[formsender::default]
      - recipe[formsender::nginx]
