name             'formsender'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures Formsender'
long_description 'Installs/Configures Formsender and its various dependencies'
version          '0.1.6'

depends 'build-essential'
depends 'git'
depends 'osl-nginx'
depends 'python-webapp'
depends 'selinux_policy'
depends 'yum-ius'

supports 'centos', '~> 7.0'
