name             'formsender'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'apache2'
description      'Installs/Configures formsender'
long_description 'Installs/Configures formsender'
version          '0.1.0'

name             'git'
version          '0.1.0'
